.gitignore, Makefile
Fixes #17 .
See also: http://stackoverflow.com/a/33171336
=> Use $(MAKE) to utilize Make jobserver

tools/minicargo/manifest.h
=> Include <functional>

Makefile
=> Small patch fix #37

tools/testrunner/main.cpp
Note: I’m not C++ developer, so I just _hope_ that I coded it right.
=> TestRunner - Add option --fail-fast, don’t fail fast by default

samples/test/gcc5_codegen_bug.rs, src/hir_expand/vtable.cpp, src/trans/codegen.cpp, src/trans/codegen_c.cpp, src/trans/enumerate.cpp, vsproject/build_rustc_minicargo.cmd
Change summary:
- Move vtable metadata (drop/size/align) to the HIR instead of trans magic
- Fix a bunch of MSVC issues (MSVC version can now compile and run "hello, world")
- Reproduction test for GCC5 codegen issue (no fix yet)
=> Merge of `dev` branch once working

src/main.cpp, src/trans/target.cpp
Note: I haven’t tested if it actually work on aarch64 yet.
=> Add targets aarch64-linux-gnu and aarch64-unknown-openbsd 

src/expand/proc_macro.cpp
=> Fix recv_v128u procedural macro plugin decoder

README.md
Small typo fix and some formatting changes. Very impressive project, I have been following it for awhile.
=> Touch up readme

README.md
Hi,
Currently the default is 1.29 not 1.19.
=> Update README for 1.29

src/trans/codegen_c.cpp
Signed-off-by: Eddy Petrișor <eddy.petrisor@gmail.com>
=> codegen_c.[ch]pp: Typo fixes

src/trans/codegen_c.cpp
- __builtinpopcount returned the wrong result
- Overflowing multiplication functions failed to handle the case where the multiplicand was zero (causing divide by zero).
- Overflowing subtraction and addition functions did not correctly handle signed types.
- 128 bit signed right shift produced the wrong result for integers with the upper half set.
- 128 bit literals were emitted without wrapping in the struct, causing c compilation errors.
- Casts to 128 bit values did not extend the sign of the source.
=> codegen_c - Fixes for MSVC intrinsics and emulated 128 bit math.

src/trans/codegen_c.cpp
This change uses aggregate initialization when initializing constants instead of GCC statement expressions.
Initialization of statics that are zero is skipped, since they will be zero-initialized on program startup anyway. This allows zeroed statics with more than 16 levels of nesting to be compiled with out errors on MSVC.
If a static has more than 16 levels of nesting, and is not zero-initialized, MSVC will fail with:
`C1054: compiler limit: initializers nested too deeply`
=> codegen_c - use aggregate initialization instead of GCC statement expressions

src/hir/from_ast.cpp, src/trans/codegen_c.cpp
Rust supports placing the link_name attribute on statics in addition to functions.
This functionality is used in rustc itself (though only on Windows) in `libpanic_unwind/seh.rs` as
```
#[link_name = "\x01??_7type_info@@6B@"]
static TYPE_INFO_VTABLE: *const u8;
```
To support this usage, this change also uses the linker alternatename option instead of #define when emitting C code on MSVC.
=> Add support for link_name attribute on statics

src/trans/codegen_c.cpp
which needs to be installed. command is a posix builtin.
=> codegen_c: use command -v instead of which

rustc-1.39.0-src.patch
Upstream commmit: https://github.com/rust-lang/llvm-project/commit/98b1752888c0282bf5504b67484b92d8d069f1b8
=> Add gcc-10 patch for LLVM.

run_rustc/Makefile
=> Use `$(DYLIB_EXT)` in one more place

run_rustc/Makefile
Patch adapted from https://github.com/thepowersgang/mrustc/pull/192
=> Set correct script-overrides folder on MacOS

src/mir/from_hir_match.cpp
=> MIR From HIR Match - Include missing <limits> header

src/hir/from_ast.cpp, tools/dump_hirfile/main.cpp
Here a two places where it should be dump:
- inside `dump_hirfile`;
- inside `from_ast.cpp`.
=> Dump loaded `lang_item`s from hir

src/trans/target.cpp, tools/common/target_detect.h
This was tested on a HiFive Unmatched board with rust-1.54.
=> Add support for riscv64

README.md
Make it more clear for future users, might help get some bug fixes in if it's clearer about how to set it up.
=> Note PARLEVEL in README
