- Makefile
Make test will now download rustc on a clean clone
> Makefile: make rustc-nightly directory a direct depenency of test target

- src/hir/serialise_lowlevel.hpp
- src/mir/from_hir_match.cpp
It gave me a build error when I tried to compile it on gcc 6.2.
Also, if you are interested, this is a list of compilation warnings I've encountered with the compiler version: http://pastebin.com/W0rXwnWF
Just mentioned those as I could remember mrustc didn't do any warnings back when I was on the older gcc version.
> Fix build on gcc 6.2

- Makefile
This is simply the `sed` fix, starting to get it to work on macOS.
> Fix sed to work across unices

- .travis.yml
Travis CI has moved from Precise to Trusty.
Since Trusty has CMake 3.2.2 by default, manual update isn't needed anymore.
> Remove CMake update

- src/hir/from_ast.cpp
- src/trans/codegen_c.cpp
Use `uint64_t` for enums with `repr(u64)`.
> Fix enums with `repr(u64)`

- src/main.cpp
GCC 6.4 on Alpine incorrectly deduces the type returned from
::std::strchr(const char *, char)
as 'char *', instead of 'const char *', which causes the wrong constructor
to be used.
Closes #32.
> main - fix incorrect type deduction with some gcc versions

- Makefile
There’s no target `rust_tests-run-pass`, only `RUST_TESTS-run-pass`.
> Makefile - Fix invalid dependency of target rust_tests

- .gitignore
- Makefile
- src/hir/hir.hpp
- src/hir/type.cpp
- src/include/tagged_union.hpp
- src/main.cpp
- src/mir/mir.cpp
- src/mir/optimise.cpp
- src/trans/codegen.cpp
- src/trans/codegen.hpp
- src/trans/codegen_c.cpp
- src/trans/codegen_mmir.cpp
- src/trans/main_bindings.hpp
- src/trans/target.cpp
- src/trans/target.hpp
- tools/minicargo/Makefile
- tools/minicargo/build.cpp
- tools/minicargo/build.h
- tools/minicargo/debug.cpp
- tools/minicargo/main.cpp
- tools/standalone_miri/hir_sim.cpp
- tools/standalone_miri/lex.cpp
- tools/standalone_miri/lex.hpp
- tools/standalone_miri/module_tree.cpp
- tools/standalone_miri/module_tree.hpp
- vsproject/build_rustc_minicargo.cmd
- vsproject/build_rustc_minicargo_mmir.cmd
- vsproject/mrustc.vcxproj
- vsproject/mrustc.vcxproj.filters
Contains the structure required for `standalone_miri` to work. This mainly replaces the slap-dash struct size calculation and codegen_c's nonzero enum optimisation with a more generalised approach.
Still has issues with warnings in the generated C (likely related to handling of negatives in enum variants).
Waiting on a full integration test pass before merge.,
> Merge "common_layout" branch

- src/expand/proc_macro.cpp
- src/main.cpp
- src/trans/target.cpp
Hi --
This pull request allows a working mrustc to build on OpenBSD (at least, OpenBSD/amd64).
Not included in this are tweaks to the build system to get mrustc to do its build-checking with rust, because that is quite invasive and I'm still unsure about the best way to proceed with upstreaming that.
> Add OpenBSD support.

- minicargo.mk
This is wrapped again and becomes unquoted when used in LLVM_CMAKE_OPTS,
breaking the build:
[...]
cd rustc-1.19.0-src/build && cmake -D LLVM_TARGET_ARCH=x86_64 -D LLVM_DEFAULT_TARGET_TRIPLE=x86_64-unknown-linux-gnu
-D LLVM_TARGETS_TO_BUILD=""X86;ARM;AArch64" -D " -D LLVM_ENABLE_ASSERTIONS=OFF -D LLVM_INCLUDE_EXAMPLES=OFF -D
LLVM_INCLUDE_TESTS=OFF -D LLVM_INCLUDE_DOCS=OFF -D LLVM_ENABLE_ZLIB=OFF -D LLVM_ENABLE_TERMINFO=OFF -D
LLVM_ENABLE_LIBEDIT=OFF -D WITH_POLLY=OFF -D CMAKE_CXX_COMPILER="g++" -D CMAKE_C_COMPILER="gcc" -D
CMAKE_BUILD_TYPE=RelWithDebInfo ../src/llvm
CMake Error: The source directory "/home/aclemons/workspace/mrustc/rustc-1.19.0-src/build/LLVM_TARGETS_TO_BUILD=X86"
does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
/bin/sh: ARM: command …
> Remove quotes from LLVM_TARGETS declaration in minicargo.mk

- src/trans/target.cpp
- tools/common/target_detect.h
This adds initial support for m68k, currently on Linux only. With these changes, I am able to build mrustc on qemu-m68k.
There are some alignment issues that need to be sorted out due to the fact that the natural alignment on m68k is 16 bits and not 32 bits, despite being a 32-bit architecture. I will address those issues in future patches.
> Trans - Add initial support for m68k

- src/ast/expr.hpp
- src/expand/derive.cpp
- src/hir/expr.hpp
- src/hir_typeck/expr_cs.cpp
- src/include/synext_decorator.hpp
- src/include/synext_macro.hpp
In many situations, objects are deleted by deleting a pointer to their base class. In the previous code, these destructors were non-virtual. This violates a C++ rule (so it's undefined behavior), and on some platforms (such as Clang with -fsized-deallocation), this violation is detected and causes mrustc to abort.
The fix is simple; mark the relevant destructors as virtual.
> Mark destructors on base classes as virtual

- src/trans/target.cpp
For historic reasons, m68k uses 16-bit alignment for all types it supports.
The output of the test program from #83 is:
m68k (gcc 8.2.0):
```
Type         Alignment/Bytes  Size/Bytes
int8_t       1                1
int16_t      2                2
int32_t      2                4
int64_t      2                8
__int128     not supported
uint8_t      1                1
uint16_t     2                2
uint32_t     2                4
uint64_t     2                8
float        2                4
double       2                8
long double  2                12
size_t       2                4
off_t        2                4
void*        2                4
```
> Trans - Fix alignment values for m68k

- samples/test/issue-mrustc-103.rs
- src/macro_rules/parse.cpp
> Allow square brackets in macro definitions

- tools/minicargo/manifest.cpp
So I started by checking if mrustc is vulnerable to the cargo advisory[1].
from this line it seems like it's not: https://github.com/thepowersgang/mrustc/blob/ebd8edeb4f1861943cc82d310564b1f592e63272/tools/minicargo/manifest.cpp#L705
Anyway I decided to just add support for renaming. tested it locally and it works correctly.
not sure where/how to add tests here for minicargo.
[1] https://blog.rust-lang.org/2019/09/30/Security-advisory-for-cargo.html
> Add support for crates renaming

- Makefile
cd to $(RUSTCSRC) not $(RUSTSRC)
> Fix typo previously breaking nightly build

- tools/minicargo/manifest.cpp
Make sure we read the whole line and not truncate on the first space.
> Implement cargo:rustc-flags

- src/expand/format_args.cpp
Formatted strings that included null literals dropped any characters past (and including) the null literal.
For example,
`println!("Hello\0World");`
prints "Hello", when it should print "Hello World" (with a \0 separating the words).
This change fixes the bug by using the length of the string rather than detecting a null terminator when processing.
This bug caused mrustc-compiled cargo to randomly crash about 20% of the time with the error "failed to create jobserver" on Windows because it caused a non-null terminated string to be passed for the name of the semaphore.
> Expand - Fix for macro format args for strings including null literals

- src/expand/proc_macro.cpp
This change adds support for invoking procedural macros on Windows using Win32 APIs.
> Expand - add support for invoking procedural macros on Windows

- tools/minicargo/manifest.cpp
Build dependency lines containing a `-` character were ignored. This caused breaks when the dependency line contained a path to a directory with a `-` in it (such as `output-1.29.0`).
This change resolves the issue by removing the check for `-`. Removing the check didn't appear to break anything, so I'm unsure of the intent of the check.
> minicargo - Allow build.rs to specify dependencies with '-'

- src/trans/codegen_c.cpp
The default stack size of 1MB on MSVC causes an mrustc-compiled rustc to hit stack overflow. This change increases the stack size to 8MB.
> codegen_c - Increase default stack size on MSVC

- src/trans/codegen_c.cpp
`Compiler::Gcc` has a check to only add `.o` files if the extern crate came from an `.rlib`. This change adds a similar check for MSVC.
> codegen_c - MSVC: only reference obj files coming from rlibs

- src/trans/codegen_c.cpp
* codegen_c targeted some functions (mostly -NoFence/Acquire/Release variants) that doesn't exist on MSVC.
* 8 bit arithmetic operations produced the wrong return value. The operations should return the original value, not the modified value.
This change adds `#defines` for the missing operations; mapping the NoFence/Acquire/Release variants to the unsuffixed version when not available.
The 8 bit operations are fixed by using the 8 bit functions.
> codegen_c - fixes for MSVC atomics

- Makefile
- run_rustc/Makefile
- tools/dump_hirfile/Makefile
- tools/minicargo/Makefile
- tools/mir_opt_test/Makefile
- tools/standalone_miri/Makefile
Macro MAKE is defined in POSIX make:
https://pubs.opengroup.org/onlinepubs/9699919799/utilities/make.html#tag_20_76_13_09
On my system, `make` is BSD make and `gmake` is GNU make. Because mrustc uses the GNU make syntax, I must explicitly call `gmake` when building it. The issue is that `gmake` will execute `make`, which is not the GNU version. So by using the standard variable, when I execute `gmake`, `MAKE` variable would automatically be set to `gmake`. This behavior solves my issue.
Thank you.
> make: Replace make by $(MAKE)

- src/trans/codegen_c.cpp
'-' is not a valid char for environment variable, use '_' instead.
eg. CC_x86_64_linux_gnu instead of invalid CC-x86_64-linux-gnu.
> Fix $CC+triple lookup

- src/trans/codegen_c.cpp
Instead of using $CC-triple, triple-gcc, $CC, gcc,
Use $CC-triple, $CC, triple-gcc, gcc.
Makes it easier to override the compiler for every possible triple.
> Change the order in which GCC is searched

- src/macro_rules/eval.cpp
`macro_rules!` macros that matched items failed to match `union`s because the parser did not account for the union having a name.
For example, the following macro failed to accept union type definitions:
```rust
macro_rules! __item {
($i:item) => {
$i
};
}
```
> Fix macro_rules macros that match unions

- src/include/range_vec_map.hpp
Without `<cstddef>`, building with GCC 5/6 produces the error:
```
error: 'ptrdiff_t' does not name a type
```
> Fix build error (ptrdiff_t) with GCC 5/6

- src/expand/mod.cpp
GCC 5 has trouble with an `auto` loop variable name shadowing a variable used in the loop array expression.
> Fix build error with GCC 5

- src/trans/target.cpp
- tools/common/target_detect.h
Note, I couldn't get a complete build to work... Got as far as `(95/96) BUILDING cargo v0.30.0` though.
```
[RUSTC] -o output/prefix-s/lib/rustlib/powerpc64le-unknown-linux-gnu/lib/libcore.rlib
make: *** [Makefile:120: output/prefix-s/lib/rustlib/powerpc64le-unknown-linux-gnu/lib/libcore.rlib] Segmentation fault
```
> Add initial support for ppc64

- src/parse/lex.cpp
Compilation fails with GCC 11 without this change.
> Lex - include missing <limits> header

- tools/common/path.cpp
- tools/minicargo/build.cpp
When path to a folder where mrustc huge the hardcoded buffer for `1024` char might not be enoug.
When it happened it corrupts memmory which leads to segfault.
I have no idea how to get `PATH_MAX` on windows => I've touched only not windows build.
> Fixed segmentation fault on huge paths

- Makefile
- bnf/Makefile
- tools/common/Makefile
- tools/dump_hirfile/Makefile
- tools/minicargo/Makefile
- tools/mir_opt_test/Makefile
- tools/standalone_miri/Makefile
- tools/testrunner/Makefile
This commit added `CXXFLAGS_EXTRA` at each `Makefile` and also introduce a brand new environment variable `LINKFLAGS_EXTRA` which can be used to adjust linking options.
> Added `LINKFLAGS_EXTRA` and `CXXFLAGS_EXTRA`

- run_rustc/Makefile
- rustc-1.54.0-src.patch
- script-overrides/stable-1.54.0-macos/build_compiler_builtins.txt
- script-overrides/stable-1.54.0-macos/build_libc.txt
- script-overrides/stable-1.54.0-macos/build_std.txt
- script-overrides/stable-1.54.0-macos/build_unwind.txt
- src/trans/codegen_c.cpp
- src/trans/target.cpp
- tools/common/target_detect.h
Here, two small patches that allows me to build rust on macOS 12.1 as
```
env OPENSSL_DIR=/opt/local/libexec/openssl11 ./build-1.54.0.sh
env RUSTC_VERSION=1.54.0 MRUSTC_TARGET_VER=1.54 OUTDIR_SUF=-1.54.0 make -C run_rustc all
```
> Bootstrapping for 1.54.0 for macOS 

- run_rustc/Makefile
`$(LIBDIR_2)libtest.rlib` is used `$(BINDIR)cargo` but doesn't depend on it.
> Missed dependency to build run-rustc

- src/trans/target.cpp
I've used the same cpu which is used by Rust: `core2` for x86_64[1] and `yonah` for i686[2]. I also used `mtine` instead of `mcpu` because it was deprecated at gcc since version 5[3].
It closes https://github.com/thepowersgang/mrustc/issues/214
I also added missed `i686-apple-darwin` target.
Footnotes:
[1]  https://github.com/rust-lang/rust/blob/1.54.0/compiler/rustc_target/src/spec/x86_64_apple_darwin.rs
[2]  https://github.com/rust-lang/rust/blob/1.54.0/compiler/rustc_target/src/spec/i686_apple_darwin.rs
[3]  https://github.com/gcc-mirror/gcc/commit/9d913bbf3fc996874649168d7d144a642012ac9b
> Enforce `-mtune=core2` and `-mtune=yonah` on macOS

- src/span.cpp
`exit()` or `abort()` never flushes the stream buffer that may lead to a crash without any explanation.
> Flush error stream before death

- Makefile
- src/trans/target.cpp
- tools/common/target_detect.h
mrustc disagrees on the size of one type (`union u_ZRG3c3std9panickingh0134Data2gG2c3std5panic16AssertUnwindSafe1gG3c17rustc_incremental7persist4loadh7closure16load_dep_g$d67c7ee6`) when building rustc 1.29.0, which, when ignored (or, indeed, `__attribute__((packed))` away), produces a rustc that panics with
```
thread 'main' panicked at 'assertion failed: ((probe).index() != idx_end)', rustc-1.29.0-src/src/libstd/collections/hash/map.rs:541:53
```
rustc may be terminally broken, but this mrustc does work for simple x32 executables, so I'm opening this PR either way, could be useful for someone smarter than me
> Mostly x32 fixes

- tools/standalone_miri/miri_extern.cpp
The fail:
```
[CXX] miri_extern.cpp
miri_extern.cpp:630:20: error: no matching function for call to 'clock_gettime'
int rv_i = clock_gettime(clk_id, reinterpret_cast<struct timespec*>(tp_vr.data_ptr_mut()));
^~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/time.h:178:5: note: candidate function not viable: no known conversion from 'unsigned int' to 'clockid_t' for 1st argument
int clock_gettime(clockid_t __clock_id, struct timespec *__tp);
^
miri_extern.cpp:749:27: error: use of undeclared identifier 'memrchr'; did you mean 'memchr'?
const void* ret = memrchr(ptr, c, n);
^~~~~~~
memchr
```
> A few trivial fixes that allows build standalone_miri on macOS

- minicargo.mk
It's now possible to override MINICARGO and LLVM_CONFIG to use dependencies from outside the source tree. This is helpful for iterating on packaging, as the bootstrap can be split up into multiple packages.
> Allow using system-installed LLVM

- tools/standalone_miri/miri_extern.cpp
`F_DUPFD_CLOEXEC` was introduced in macOS 10.7 like this:
```
#if __DARWIN_C_LEVEL >= 200809L
#define	F_DUPFD_CLOEXEC		67	/* mark the dup with FD_CLOEXEC */
#endif
```
> Use `F_DUPFD_CLOEXEC` only on macOS 10.7+

- run_rustc/Makefile
Like b8ea12a041d37441bc8de48a110d0b0bd449a793, just in another place.
> Also allow system-provided llvm-config in run_rustc

- src/include/tagged_union.hpp
Here two fixes:
- the correct suppression for clang's nitpicking
- minor fixes for `typeid` side effect
> Fixed some warnings from `clang` (ref #236)

- src/ast/expr.cpp
- src/ast/expr.hpp
- src/ast/expr_ptr.hpp
- src/expand/mod.cpp
- src/hir/expr.cpp
- src/hir/expr.hpp
- src/hir/from_ast_expr.cpp
- src/hir_typeck/expr_cs.cpp
- src/hir_typeck/expr_cs__enum.cpp
Can build it now with `-Werror=potentially-evaluated-expression`
> Removed side effect from typeid call (ref #236)

- src/hir_typeck/monomorph.hpp
Can compile it with `-Werror=delete-abstract-non-virtual-dtor`, and after that make full bootstrap of rustc.
> Add a default virtual destructor to `Monomorphiser` (ref #236)

- Makefile
It fails as:
```
cc1plus: note: unrecognized command-line option '-Wno-unknown-warning-option' may have been intended to silence earlier diagnostics
```
> Remove unknown flag for gcc12

- src/parse/lex.cpp
- tools/minicargo/build.cpp
Let assume that `::std::istream` marks itself as reached `EOF` after reading the last character from file which is `':'` in case of minicargo's `build.cpp`.
This leads to missing `':'` because the next call of `get_token_int()` returns `""` because `ifp.eof()` is `true`, instead of returning `":"` as it should.
This missed `':'` leads to assert that dependency file aren't well formatted on some wired system.
The same happened with `Lexer::getc_byte` when `m_istream.get()` returns not `EOF` but marks stream as reached `EOF` that means the next read returns `EOF`.
Thus, this fixes: https://github.com/thepowersgang/mrustc/issues/284
> Compatibility with macOS 10.7

- tools/minicargo/build.cpp
Adds argument escaping in minicargo for Windows based on the approach described here:
https://docs.microsoft.com/en-us/archive/blogs/twistylittlepassagesallalike/everyone-quotes-command-line-arguments-the-wrong-way
> minicargo - fix argument quoting on Windows

- src/include/tagged_union.hpp
- src/mir/from_hir_match.cpp
- tools/backend_c/backend_c.cpp
A few minor changes necessary to make `mrustc` build with VS2022.
Does not actually change any of the projects to build with VS2022.
> Windows build - fix compilation errors on VS2022

- rustc-1.54.0-src.patch
> Never use section on aarch64 (#277)

- src/trans/target.cpp
- tools/common/target_detect.h
See: https://github.com/thepowersgang/mrustc/issues/300#issuecomment-1506104456
@thepowersgang Could you please check this?
P. S. As I mention in the topic, Darwin on ppc32 _may_ need 4-byte bools, since Apple ABI defines that: http://personal.denison.edu/~bressoud/cs281-s07/MacOSXLowLevelABI.pdf
Not sure if that should apply to Rust code though.
> Fix targets for Darwin PowerPC

- src/hir/type.cpp
- src/mir/mir.hpp
- tools/common/toml.h
Just one of some patches needed to ensure Rust builds with newer GCC and Clang, the other patches involve modifying the rust source code itself.
> Add missing includes for GCC >= 13, Clang

- rustc-1.29.0-src.patch
Fixes building with GCC 12.x. The issue is the missing `<limits>` header in `llvm/lib/Demangle/ItaniumDemangle.cpp`.
In current LLVM, the <limits> header is included via `<ItaniumDemangle.h>, added in https://github.com/llvm/llvm-project/commit/1f9e18b6565fd1bb69c4b649b9efd3467b3c7c7d, however that header doesn't exist in the LLVM revision (looks like 7.0.0 ?) used here.
This was also reported in #293. To reproduce:
```bash
apt install gcc g++ git make patch libz-dev curl cmake python3
g++ --version
g++ (Ubuntu 12.3.0-3ubuntu1) 12.3.0
git clone https://github.com/thepowersgang/mrustc
cd mrustc
make RUSTCSRC
make -f minicargo.mk
make -f Makefile all
make[1]: Entering directory '/mrustc'
[CXX] -o .obj/main.o
[CXX] -o .obj/span.o
[CXX] -o .obj/rc_string.o
[CXX] -o .obj/debug.o
-- Generating …
```
> 1.29.0: patch <limits> into LLVM to fix GCC 12 compilation

- README.md
This is required to build llvm in rustc. i.e without:
```bash
apt install gcc g++ git make patch libz-dev curl cmake
git clone https://github.com/thepowersgang/mrustc
cd mrustc
RUSTC_VERSION=1.54.0 make RUSTCSRC
RUSTC_VERSION=1.54.0 make -f minicargo.mk
make -f Makefile all
make[1]: Entering directory '/mrustc'
[CXX] -o .obj/main.o
...
-- OCaml bindings disabled.
-- LLVM host triple: x86_64-unknown-linux-gnu
-- LLVM default target triple: x86_64-unknown-linux-gnu
-- Building with -fPIC
CMake Error at /usr/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
Could NOT find Python3 (missing: Python3_EXECUTABLE Interpreter)
Call Stack (most recent call first):
/usr/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE) …
```
> doc: add python3 to deps

- README.md
This is required to find crate deps, i.e libssl. i.e:
```bash
make -C run_rustc
...
thread 'main' panicked at "
Could not find directory of OpenSSL installation, and this "-sys" crate cannot
proceed without this knowledge. If OpenSSL is installed and this crate had
trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
compilation process.
Make sure you also have the development packages of openssl installed.
For example, "libssl-dev" on Ubuntu or `openssl-devel` on Fedora.
If you are in a situation where you think the directory *should* be found
automatically, please open a bug at https://github.com/sfackler/rust-openssl
and include information about your system as well as this message.
$HOST = x86_64-linux-gnu
$TARGET = x86_64-linux-gnu
openssl-sys = 0.9.35
", …
```
> doc: add `pkg-config` to build deps

- rustc-1.19.0-src.patch
- rustc-1.29.0-src.patch
- rustc-1.39.0-src.patch
- rustc-1.54.0-src.patch
This should fix #298. `1.39.0` seems to work fine as-is, so left it for now.
An alternative would be to update the docs to instruct macOS users to avoid "Apple patch" i.e:
```bash
patch 2.0-12u11-Apple
```
and instead install and use something like GNU patch. i.e `brew install gpatch`.
Happy to do that in this PR if you'd prefer.
> rustc: regenerate patches for 1.29.0 & 1.54.0

- rustc-1.54.0-src.patch
Compiling on aarch64 (using `./build-1.54.0.sh`), with GCC 13.2.1, I currently see the following failure:
```bash
In file included from /root/mrustc/rustc-1.54.0-src/src/llvm-project/llvm/lib/Support/Signals.cpp:14:
/root/mrustc/rustc-1.54.0-src/src/llvm-project/llvm/include/llvm/Support/Signals.h:119:8: error: variable or field ‘CleanupOnSignal’ declared void
119 |   void CleanupOnSignal(uintptr_t Context);
|        ^~~~~~~~~~~~~~~
/root/mrustc/rustc-1.54.0-src/src/llvm-project/llvm/include/llvm/Support/Signals.h:119:24: error: ‘uintptr_t’ was not declared in this scope
119 |   void CleanupOnSignal(uintptr_t Context);
|                        ^~~~~~~~~
/root/mrustc/rustc-1.54.0-src/src/llvm-project/llvm/include/llvm/Support/Signals.h:18:1: note: ‘uintptr_t’ is defined in header …
```
> 1.54.0: patch LLVM for GCC 13.2.1

- src/trans/target.cpp
- tools/common/target_detect.h
Simple patch to add musl support.
There is no reliable way to detect musl I am aware of, but we can detect glibc which defines _USE_GNU, then we fall back to musl.
This successfully builds on alpine. 
LMK if this approach works for you, and I can at least take a look at CI.
Linking #324
> musl support

- tools/common/debug.h
format_to_stream uses operator<< on vectors but it is defined earlier.
Fixes: https://github.com/thepowersgang/mrustc/issues/336
> Debug - Declare operator<< before its use.

- TestRustcBootstrap.sh
Use stage3 instead of stage2 to create the tarballs - although they are meant to be identical with regards to binaries included in stage2, stage3 builds more, including cargo.
> Generate reproducible output tarballs and report if they are identical

- tools/common/target_detect.h
* tools/common/target_detect.h: Fix typo in powerpc64le-* triplets.
> Fix target-name for powerpc64le.

- src/parse/expr.cpp
> Allow `&data[..crate::VALUE]`

- README.md
- This project doesn't build with `BSD make`, so require `GNU make` specifically
- Currently building `libstd` with `clang` fails on OpenBSD, so add a note about using `gcc`
- And minor grammar fixes
> Minor README changes/fixes

- src/expand/asm.cpp
- src/hir/asm.hpp
- src/trans/codegen_c.cpp
- src/trans/target.cpp
- tools/minicargo/build.cpp
With these changes, I can build mrustc for x86_64-unknown-openbsd and generate binaries for riscv64-unknown-linux-musl.
I have an accompanying C cross-compiler for the target.
I'm also planning on making ARM work.
> RISC-V Cross-Compilation

- Makefile
- TestRustcBootstrap.sh
- minicargo.mk
- tools/minicargo/manifest.h
I was able to build and use mrustc on *OpenBSD*, but with a few changes.
To be able to use mrustc, I had to set `CC=egcc` (gcc-11.2.0),
because `compiler_builtins` would emit wrong assembly for clang.
Please test my changes, so they don't affect other systems.
<details>
<summary>compiler_builtins failure with clang:</summary>
```
--- BUILDING compiler_builtins v0.1.101 (15.8% 1r,0w,15b,3c/19t)
> tools/bin/mrustc rustc-1.74.0-src/vendor/compiler_builtins/src/lib.rs -o output-1.74.0/libcompiler_builtins-0_1_101_H10c.rlib -C emit-depfile=output-1.74.0/libcompiler_builtins-0_1_101_H10c.rlib.d --cfg debug_assertions -O -L output-1.74.0 --cfg feature="compiler-builtins" --cfg feature="rustc-dep-of-std" --cfg feature="core" --cfg feature="dep:core" --crate-name compiler_builtins --crate-type …
```
> Fix building on OpenBSD

- src/ast/path.hpp
- src/ast/types.hpp
- src/debug.cpp
- src/hir/generic_ref.hpp
- src/hir/type_ref.hpp
- tools/minicargo/build.cpp
This fixes compile issues when using GCC 15 (gcc (GCC) 15.0.1 20250329 (Red Hat 15.0.1-0)):
```bash
[CXX] -o .obj/debug.o
src/debug.cpp: In function ‘std::ostream& operator<<(std::ostream&, const FmtEscaped&)’:
src/debug.cpp:163:13: error: ‘uint8_t’ was not declared in this scope
163 |             uint8_t v = *s;
```
See porting to GCC 15 (https://gcc.gnu.org/gcc-15/porting_to.html):
> In particular, the following headers are used less widely within
> libstdc++ and may need to be included explicitly when compiling with GCC 15:
> <stdint.h> (for int8_t, int32_t etc.) and <cstdint> (for std::int8_t, std::int32_t etc.)
> refactor: add missing std lib includes
